(() => {
  const $ = (s, p = document) => p.querySelector(s);
  const $$ = (s, p = document) => [...p.querySelectorAll(s)];
  $('#year').textContent = new Date().getFullYear();
  const menu = $('.menu-toggle'), mobile = $('.mobile-nav');
  menu?.addEventListener('click', () => { const open = mobile.classList.toggle('open'); menu.setAttribute('aria-expanded', open); mobile.setAttribute('aria-hidden', !open); });
  $$('a[href^="#"]').forEach(a => a.addEventListener('click', () => mobile?.classList.remove('open')));
  const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
  if (!reduced && 'IntersectionObserver' in window) { const observer = new IntersectionObserver(entries => entries.forEach(e => e.isIntersecting && (e.target.classList.add('visible'), observer.unobserve(e.target))), {threshold:.12}); $$('.reveal').forEach(x => observer.observe(x)); } else $$('.reveal').forEach(x => x.classList.add('visible'));
  const canvas = $('#core-canvas');
  if (canvas && !reduced) { const ctx = canvas.getContext('2d'); let points=[], pointer={x:.5,y:.5}; const resize=()=>{const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.scale(d,d);points=Array.from({length:innerWidth<700?22:42},()=>({x:Math.random()*r.width,y:Math.random()*r.height,vx:(Math.random()-.5)*.22,vy:(Math.random()-.5)*.22}));}; resize(); addEventListener('resize',resize); canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();pointer={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}); const draw=()=>{const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height); const cx=r.width*(.5+(pointer.x-.5)*.04),cy=r.height*(.5+(pointer.y-.5)*.04); const glow=ctx.createRadialGradient(cx,cy,5,cx,cy,110);glow.addColorStop(0,'rgba(180,195,255,.85)');glow.addColorStop(.12,'rgba(115,135,255,.35)');glow.addColorStop(1,'rgba(115,135,255,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,r.width,r.height);points.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>r.width)p.vx*=-1;if(p.y<0||p.y>r.height)p.vy*=-1;points.forEach(q=>{const dx=p.x-q.x,dy=p.y-q.y,dist=Math.hypot(dx,dy);if(dist<105){ctx.strokeStyle=`rgba(145,169,255,${.14*(1-dist/105)})`;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}});ctx.fillStyle='rgba(210,220,255,.8)';ctx.beginPath();ctx.arc(p.x,p.y,1.4,0,7);ctx.fill()});ctx.fillStyle='#e8ebff';ctx.beginPath();ctx.arc(cx,cy,5,0,7);ctx.fill();requestAnimationFrame(draw)};draw(); }
  const choices = [{sales:['Lead qualification automation','CRM enrichment','Personalized proposal workflow'],operations:['Workflow handoff automation','Operational reporting','Human approval checkpoints'],support:['Support triage agent','Knowledge assistant','Response routing'],knowledge:['Internal knowledge assistant','Document intelligence','Research workflow']}]; let answers={}; $$('.scanner-step button').forEach(btn=>btn.addEventListener('click',()=>{const step=btn.closest('.scanner-step');step.querySelectorAll('button').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');answers[step.dataset.step]=btn.dataset.value;setTimeout(()=>{step.classList.remove('active');const next=$(`.scanner-step[data-step="${+step.dataset.step+1}"]`);if(next){next.classList.add('active');$('.scanner-progress span:last-child').textContent=`0${next.dataset.step} / 03`;}else{const result=$('.scanner-result');$('.scanner-progress span:last-child').textContent='COMPLETE';const list=$('ul',result);list.innerHTML=(choices[0][answers[1]]||choices[0].operations).map(x=>`<li>${x}</li>`).join('');result.classList.add('active');}},220)}));
  const form=$('#inquiry-form'); let selected=''; $$('.form-options button').forEach(b=>b.addEventListener('click',()=>{selected=b.textContent.trim();$$('.form-options button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')})); $$('.form-next').forEach(b=>b.addEventListener('click',()=>{const step=b.closest('.form-step');if(step.dataset.formStep==='1'&&!selected){toast('Choose an area to continue.');return}if(step.dataset.formStep==='2'&&!$$('input',step).every(i=>i.checkValidity())){$('input',step).find(i=>!i.checkValidity())?.reportValidity();return}step.classList.remove('active');const next=$(`.form-step[data-form-step="${+step.dataset.formStep+1}"]`);next.classList.add('active');$('.form-step-label').textContent=`0${next.dataset.formStep} / 03`})); form?.addEventListener('submit',e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}$('.form-step.active',form)?.classList.remove('active');$('.form-top',form).style.display='none';$('.form-success',form).classList.add('active');const body = `Project: ${selected}\nName: ${form.elements.name.value}\nCompany: ${form.elements.company.value}\nEmail: ${form.elements.email.value}\n\n${form.elements.message.value}`; $('#email-brief').href = 'mailto:harshitpandey3519@gmail.com?subject=NaadiX%20project%20inquiry&body=' + encodeURIComponent(body); toast('Email draft prepared. Send it in your email app.');});
  let timer; function toast(msg){const t=$('.toast');t.textContent=msg;t.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>t.classList.remove('show'),3000)}
})();
